language: ruby
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without=development"
matrix:
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION='~> 3.8.0'
    bundler_args: "--jobs=3 --retry=3 --without='development system_tests'"
    script: bundle exec rake lint validate spec
  - rvm: 2.2.6
    env: PUPPET_VERSION='~> 4.8.0'
    script: bundle exec rake lint validate spec
  - rvm: 2.4.3
    env: PUPPET_VERSION='~> 5.0.0'
    script: bundle exec rake lint validate spec
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos6 BEAKER_debug=true
    script: bundle exec rake beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos7 BEAKER_debug=true
    script: bundle exec rake beaker
